baseurl: "https://project-primera.github.io"
title: "Project Primera Blog"
theme: "hugo-github-markdown-style"
languageCode: "ja"
hasCJKLanguage: true
enableGitInfo: true
footnotereturnlinkcontents: "↩"

params:
  paginate: 50
  description: "Project Primeraが開発運営を行うツールのアナウンスを行います。"
  footer:
    poweredByHugo: true
    themeInformation: true
    text: "&copy; 2018 [Project Primera](https://github.com/project-primera) | [プライバシーポリシーと免責事項](/privacy)"
  gtagId: "G-MP0P5VS342"
  hatenaBookmark: false
  hatenaStar: true
  alternativeTweet: true
  editThis:
    gitHub:
      repo: project-primera/project-primera.github.io
      branch: main
    gitHubDev:
      repo: project-primera/project-primera.github.io
      branch: main
    vsCode:
      url: https://vscode.dev/github/project-primera/project-primera.github.io/


menu:
  main:
    - name: すべてのカテゴリー
      url: "/categories/"
      params:
        color: "informational"
      weight: 1
    - name: すべてのタグ
      url: "/tags/"
      params:
        color: "informational"
      weight: 2
    - name: RSS Feed
      url: "/index.xml"
      params:
        color: "orange"
      weight: 3
    - name: "OngekiScoreLog"
      url: "https://ongeki-score.net"
      params:
        label: "ongeki--score.net"
        color: "14bfdf"
        target: "_blank"
      weight: 4
    - name: GitHub
      url: "https://github.com/project-primera"
      params:
        label: /
        message: project--primera
        logo: github
        color: "181717"
        target: "_blank"
      weight: 11
    - name: Twitter
      url: "https://twitter.com/ongeki_score"
      params:
        label: /
        message: ongeki_score
        logo: twitter
        color: "1DA1F2"
        target: "_blank"
      weight: 12

markup:
  highlight:
    codeFences: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

caches:
  getjson:
    dir: ":cacheDir/:project"
    maxAge: "10s"
